- name: Configurer SNMP sur les routeurs
  hosts:
    - r1
    - r2
  gather_facts: no
  tasks:
    - name: Configurer la communauté SNMP en lecture seule
      cisco.ios.ios_config:
        lines:
          - snmp-server community super_commu ro

    - name: Configurer l'hôte SNMP pour envoyer les traps
      cisco.ios.ios_config:
        lines:
          - snmp-server host 10.3.30.100 version 2c super_commu
